"""Verify that every document required by the spec exists and is not a stub.

Guards against the "documentacion aspiracional" anti-goal from two directions: the file
must exist, and it must have real content (headings, minimum length, no placeholder
markers).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Required by section 8 of PROMPT_AGENT_FORGE.md.
REQUIRED: tuple[str, ...] = (
    "README.md",
    "QUICKSTART.md",
    "CLAUDE.md",
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "LICENSE",
    "docs/ARCHITECTURE.md",
    "docs/CONNECTORS.md",
    "docs/CHANNELS.md",
    "docs/ORCHESTRATORS.md",
    "docs/MEMORY.md",
    "docs/KNOWLEDGE.md",
    "docs/GOVERNANCE.md",
    "docs/THREAT_MODEL.md",
    "docs/OBSERVABILITY.md",
    "docs/EVALS.md",
    "docs/DEPLOYMENT.md",
    "docs/RUNBOOK.md",
    "docs/WELL_ARCHITECTED.md",
    "docs/GLOSSARY.md",
    "docs/CODING_STANDARDS.md",
    "docs/VERSIONING.md",
    "docs/adr/ADR-000-template.md",
    "docs/memory/DECISIONS_LOG.md",
    "docs/memory/OPEN_QUESTIONS.md",
    "docs/memory/LESSONS_LEARNED.md",
)

# Generated by `make repo-graph`; required for the DoD but not for `make check`.
GENERATED: tuple[str, ...] = ("docs/REPO_MAP.md",)

MIN_CHARS = 400
# TODO/FIXME/XXX/TBD are matched case-SENSITIVELY on purpose: "todo" is an ordinary
# Spanish word and these documents are in Spanish.
PLACEHOLDER = re.compile(r"\bTODO\b|\bFIXME\b|\bXXX\b|\bTBD\b|<placeholder>")
PLACEHOLDER_CI = re.compile(r"lorem ipsum|por (?:definir|completar|escribir)", re.IGNORECASE)


def check_file(root: Path, rel: str, *, require_headings: bool = True) -> list[str]:
    """Return a list of problems with one document. Empty means healthy."""
    path = root / rel
    if not path.is_file():
        return [f"{rel}: missing"]

    text = path.read_text(encoding="utf-8", errors="replace")
    problems: list[str] = []

    if len(text.strip()) < MIN_CHARS:
        problems.append(f"{rel}: only {len(text.strip())} chars, looks like a stub")

    if require_headings and not _has_heading(text):
        problems.append(f"{rel}: no top-level heading")

    prose = _strip_code(text)
    for pattern in (PLACEHOLDER, PLACEHOLDER_CI):
        found = pattern.search(prose)
        if found:
            line = text[: found.start()].count("\n") + 1
            problems.append(f"{rel}:{line}: placeholder marker {found.group(0)!r}")

    return problems


CODE_SPAN = re.compile(r"```.*?```|`[^`\n]*`", re.DOTALL)


def _strip_code(text: str) -> str:
    """Blank out code spans, preserving offsets so line numbers stay correct.

    A document that says "nada de `TODO`" is forbidding the marker, not carrying one.
    """
    return CODE_SPAN.sub(lambda m: re.sub(r"[^\n]", " ", m.group(0)), text)


def _has_heading(text: str) -> bool:
    """True if the document has an H1, skipping YAML frontmatter (MADR uses it)."""
    body = text.lstrip()
    if body.startswith("---"):
        parts = body.split("---", 2)
        if len(parts) == 3:
            body = parts[2].lstrip()
    return body.startswith("#")


def check_adrs(root: Path) -> list[str]:
    """At least the four ADRs the spec names must exist and be accepted."""
    adr_dir = root / "docs" / "adr"
    problems: list[str] = []
    accepted = [
        p
        for p in sorted(adr_dir.glob("ADR-*.md"))
        if p.name != "ADR-000-template.md" and "status: accepted" in p.read_text(encoding="utf-8")
    ]
    if len(accepted) < 4:
        problems.append(
            f"docs/adr: {len(accepted)} accepted ADRs, the spec requires at least 4 "
            "(agentic framework, memory, broker, vector store)"
        )
    return problems


def check_decisions_log_per_phase(root: Path) -> list[str]:
    """DoD 15: DECISIONS_LOG.md must carry one entry per completed phase."""
    log = root / "docs" / "memory" / "DECISIONS_LOG.md"
    if not log.is_file():
        return ["docs/memory/DECISIONS_LOG.md: missing"]
    text = log.read_text(encoding="utf-8")
    phases = set(re.findall(r"##\s+\d{4}-\d{2}-\d{2}\s+·\s+(F\d)\b", text))
    notes = {
        m.group(1)
        for p in (root / "docs" / "memory" / "SESSION_NOTES").glob("*.md")
        if (m := re.search(r"fase-(\d)", p.name))
    }
    missing = {f"F{n}" for n in notes} - phases
    if missing:
        return [f"DECISIONS_LOG.md: no entry for phase(s) {', '.join(sorted(missing))}"]
    return []


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path())
    parser.add_argument(
        "--strict",
        action="store_true",
        help="also require generated docs (REPO_MAP.md); used in CI after repo-graph",
    )
    args = parser.parse_args(argv)
    root = args.root.resolve()

    problems: list[str] = []
    for rel in REQUIRED:
        problems.extend(check_file(root, rel, require_headings=not rel.endswith("LICENSE")))
    if args.strict:
        for rel in GENERATED:
            problems.extend(check_file(root, rel))
    problems.extend(check_adrs(root))
    problems.extend(check_decisions_log_per_phase(root))

    if problems:
        print("docs-check FAILED:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    checked = len(REQUIRED) + (len(GENERATED) if args.strict else 0)
    print(f"docs-check OK: {checked} documents present with real content")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
