"""Create a second cell that runs alongside the first. ``make new-instance``.

The point of the generator is what it does *not* do: it never touches code. A new area is
a new profile, a new ``.env`` and a Compose override with its own project name, ports and
volumes -- and that is the whole product claim. If adding an area required a code change,
this would be a framework, not a product.

Two isolation models, because both are legitimate and they answer different questions:

**Shared** (``--shared``) -- the instance brings only its own cell and joins the base
stack's networks. One Postgres, Redis, Qdrant and NATS for N cells; what keeps them apart
is the ``tenant_id`` + ``AGENT_FORGE_INSTANCE`` namespacing every key already carries,
which is precisely what that namespacing is for. Cheap: the tenth area costs one
container. Use it for several areas of one customer.

**Standalone** (the default) -- the instance clones the whole stack, its own stores
included. Harder blast radius: a corrupt Postgres cannot touch the neighbour. Use it for
tenants who require physical separation, or when one area's load should not be able to
starve another's.

The namespacing invariant holds either way. Under ``--shared`` it is the boundary; under
standalone it is defence in depth.

    uv run python scripts/new_instance.py --name ventas --tenant acme-mx --shared
    cd instances/acme-mx-ventas
    docker compose --env-file ../../.env --env-file .env --profile core up -d
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
INSTANCES = REPO_ROOT / "instances"
TEMPLATE_PROFILE = REPO_ROOT / "configs" / "agent.profile.example.yaml"

# Where the per-instance ports start. 8080 is the base cell, so the first generated
# instance takes 8180 and each one after it moves up by 100 -- enough room for the whole
# service block of an instance without overlapping the next.
PORT_BASE = 8080
PORT_STRIDE = 100
NAME_PATTERN = re.compile(r"^[a-z][a-z0-9-]{1,30}$")

ENV_TEMPLATE = """# Generated by `make new-instance NAME={name} TENANT={tenant}`.
#
# Only what differs from the base cell lives here. Everything else is inherited from the
# repository's `.env`, which is where shared infrastructure and secrets belong: two
# instances on one host share a Postgres, and duplicating its password into every
# instance directory is how one of the copies goes stale.

COMPOSE_PROJECT_NAME=agent-forge-{slug}

AGENT_FORGE_INSTANCE={name}
AGENT_FORGE_TENANT={tenant}
AGENT_FORGE_PROFILE=/app/configs/agent.profile.yaml

# Host ports. The container still listens on 8080; only the published side moves.
AGENT_API_PORT={api_port}
AGENT_PUBLIC_URL=http://127.0.0.1:{api_port}

# Evidence is per instance: one chain per tenant, and two instances writing the same
# chain would fork it, which fails verification in a way that looks like tampering.
LEDGER_PATH=/var/lib/agent-forge/ledger
{shared_env}"""

COMPOSE_TEMPLATE = """# Generated by `make new-instance NAME={name} TENANT={tenant}`.
#
# An override, not a copy. It includes the repository's compose file so a change there --
# a pinned image, a healthcheck, a resource limit -- reaches every instance. A generated
# full copy would drift from the original the first time anyone edited either.
#
#     cd instances/{slug}
#     docker compose --env-file ../../.env --env-file .env --profile core up -d
#
# Two env files, in that order: the repository's holds the shared infrastructure and its
# secrets, this one holds only what makes this instance different. Duplicating the
# secrets into every instance directory is how one of the copies goes stale.
#
# The published port comes from AGENT_API_PORT in this directory's `.env`; the base file
# already reads it, so there is nothing to override here.

include:
  - path: ../../deploy/compose/docker-compose.yml

services:
  agent-api:
    environment:
      AGENT_FORGE_INSTANCE: {name}
      AGENT_FORGE_PROFILE: /app/configs/agent.profile.yaml
    volumes:
      # This instance's profile shadows the image's default.
      - ./agent.profile.yaml:/app/configs/agent.profile.yaml:ro
      - {slug}-ledger:/var/lib/agent-forge/ledger

  ingestion-worker:
    environment:
      AGENT_FORGE_INSTANCE: {name}
      AGENT_FORGE_PROFILE: /app/configs/agent.profile.yaml
    volumes:
      - ./agent.profile.yaml:/app/configs/agent.profile.yaml:ro
      - {slug}-ledger:/var/lib/agent-forge/ledger

volumes:
  {slug}-ledger:
"""

SHARED_ENV = """
# Compose project of the BASE stack, whose networks this instance joins. Compose derives
# it from the directory the command runs in, so from the repository root it is the repo
# folder's name. Set it if you run the base stack under another project name.
BASE_COMPOSE_PROJECT=agentforge
"""

# `extends` and not `include`: include pulls in every service, so bringing the instance up
# under its own project name clones the entire stack -- the opposite of sharing. `extends`
# copies one service definition, healthcheck, cap_drop, limits and all, so this file still
# inherits changes to the base compose without inheriting its datastores.
SHARED_COMPOSE_TEMPLATE = """# Generated by `make new-instance NAME={name} TENANT={tenant}`
# with --shared.
#
# SHARED infrastructure. This file brings up only this cell; Postgres, Redis, Qdrant, NATS
# and LiteLLM belong to the base stack and are reached over its networks. What keeps two
# instances apart is the `tenant_id` + instance namespacing every key already carries --
# which is what that namespacing is for.
#
# The base stack has to be up first:
#
#     make up PROFILE=core
#     cd instances/{slug}
#     docker compose --env-file ../../.env --env-file .env --profile core up -d
#
# `extends`, not `include`: `include` would pull in every service and clone the whole
# stack under this project name. `extends` copies one service definition -- healthcheck,
# cap_drop, resource limits and all -- so this file still inherits changes to the base
# compose without inheriting its datastores.

services:
  agent-api:
    extends:
      file: ../../deploy/compose/docker-compose.yml
      service: agent-api
    # The base stack owns these. Waiting on services this project does not manage would
    # never resolve.
    depends_on: !reset []
    environment:
      AGENT_FORGE_INSTANCE: {name}
      AGENT_FORGE_PROFILE: /app/configs/agent.profile.yaml
    ports: !override
      - "127.0.0.1:{api_port}:8080"
    volumes: !override
      - ./agent.profile.yaml:/app/configs/agent.profile.yaml:ro
      - ledger-data:/var/lib/agent-forge/ledger

  ingestion-worker:
    extends:
      file: ../../deploy/compose/docker-compose.yml
      service: ingestion-worker
    depends_on: !reset []
    environment:
      AGENT_FORGE_INSTANCE: {name}
      AGENT_FORGE_PROFILE: /app/configs/agent.profile.yaml
    volumes: !override
      - ./agent.profile.yaml:/app/configs/agent.profile.yaml:ro
      - ledger-data:/var/lib/agent-forge/ledger

volumes:
  # Named explicitly so the chain is this instance's and survives the base stack being
  # recreated. Two instances writing one chain would fork it.
  ledger-data:
    name: {slug}-ledger

networks:
  frontend:
    external: true
    name: ${{BASE_COMPOSE_PROJECT:-agentforge}}_frontend
  backend:
    external: true
    name: ${{BASE_COMPOSE_PROJECT:-agentforge}}_backend
"""

README_TEMPLATE = """# Instancia `{name}` · tenant `{tenant}`

Generada por `make new-instance NAME={name} TENANT={tenant}`. **No se edito codigo.**

```bash
cd instances/{slug}
docker compose --env-file ../../.env --env-file .env --profile core up -d
curl -s http://127.0.0.1:{api_port}/health/ready | jq
```

Los dos `--env-file` y en ese orden: el del repositorio trae la infraestructura
compartida y sus secretos, el de aqui solo lo que hace distinta a esta instancia.

## Que la separa de la celula base

| Dimension | Como se separa |
|---|---|
| Datos | Cada clave en Redis, Postgres, Qdrant, Neo4j y NATS lleva `tenant_id` + instancia |
| Evidencia | Cadena hash propia, en su volumen |
| Puerto | `{api_port}` en el host; dentro del contenedor sigue siendo 8080 |
| Proyecto Compose | `agent-forge-{slug}`, asi que sus contenedores, redes y volumenes son suyos |
| Perfil | `agent.profile.yaml` en este directorio, montado sobre el de la imagen |

## Modo de aislamiento: {mode_label}

{mode_note}

## Personalizar

Edita `agent.profile.yaml`: area, persona, subgrafo, fuentes de conocimiento, mapa de
autonomia, allowlist de tools. Reinicia con `docker compose restart agent-api`. Sigue sin
tocarse codigo.
"""


SHARED_NOTE = """
Esta instancia **comparte** la infraestructura del stack base: Postgres, Redis, Qdrant,
NATS, LiteLLM y el stack de observabilidad. Trae solo su propia celula y se une a las redes
del proyecto base (`BASE_COMPOSE_PROJECT` en el `.env` de este directorio).

Lo que las separa no es el contenedor: es que **cada clave lleva `tenant_id` + instancia**
en Redis, Postgres, Qdrant, Neo4j, NATS y el ledger. Para eso se construyo ese namespacing.

El stack base tiene que estar arriba antes:

```bash
make up PROFILE=core
```

Si un tenant exige separacion fisica de los almacenes, regenera la instancia **sin**
`--shared`: cada una traera los suyos."""

STANDALONE_NOTE = """
Esta instancia es un **stack completo**: trae sus propios Postgres, Redis, OPA y
LiteLLM.
Radio de impacto mas duro —una base corrupta no toca a la vecina— a cambio de N veces la
infraestructura en el mismo host.

Para varias areas de un mismo cliente suele sobrar: regenera con `--shared` y compartiran
los almacenes, con el aislamiento que ya da el namespacing por `tenant_id` + instancia."""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--name", required=True, help="instance name, e.g. ventas")
    parser.add_argument("--tenant", required=True, help="tenant id, e.g. acme-mx")
    parser.add_argument("--area", default="", help="business area (defaults to --name)")
    parser.add_argument("--port", type=int, default=0, help="host port (default: next free)")
    parser.add_argument(
        "--shared",
        action="store_true",
        help=(
            "join the base stack's infrastructure instead of cloning it. Cheaper, and the "
            "isolation is the tenant_id + instance namespacing every key already carries"
        ),
    )
    parser.add_argument(
        "--force", action="store_true", help="overwrite an existing instance directory"
    )
    parser.add_argument("--root", type=Path, default=INSTANCES)
    return parser.parse_args(argv)


def next_port(root: Path) -> int:
    """The next port in the stride that no existing instance has taken."""
    used = set()
    for env in sorted(root.glob("*/.env")):
        for line in env.read_text(encoding="utf-8").splitlines():
            if line.startswith("AGENT_API_PORT="):
                with_value = line.split("=", 1)[1].strip()
                if with_value.isdigit():
                    used.add(int(with_value))
    port = PORT_BASE + PORT_STRIDE
    while port in used:
        port += PORT_STRIDE
    return port


def render_profile(template: str, *, name: str, tenant: str, area: str) -> str:
    """Point the example profile at this instance.

    A targeted rewrite of the identity block rather than a generated file: the example
    profile is the documented reference, comments included, and a generator that produced
    its own minimal version would quietly drop everything the reference explains.
    """
    template = _replace_persona(template, area)
    lines = template.splitlines()
    out: list[str] = []
    in_identity = False
    for line in lines:
        if line.startswith("identity:"):
            in_identity = True
            out.append(line)
            continue
        if in_identity and line and not line.startswith((" ", "#")):
            in_identity = False
        if in_identity:
            for key, value in (
                ("agent_name:", f'"asistente-{name}"'),
                ("area:", f'"{area}"'),
                ("tenant_id:", f'"{tenant}"'),
            ):
                stripped = line.strip()
                if stripped.startswith(key):
                    indent = line[: len(line) - len(line.lstrip())]
                    comment = line.split("#", 1)
                    trailing = f"  #{comment[1]}" if len(comment) > 1 else ""
                    line = f"{indent}{key} {value}{trailing}"
                    break
        out.append(line)
    header = (
        f"# Perfil de la instancia `{name}` (tenant `{tenant}`).\n"
        f"# Generado por `make new-instance`. Editable: es configuracion, no codigo.\n"
    )
    return header + "\n".join(out) + "\n"


def _replace_persona(template: str, area: str) -> str:
    """Swap the example persona for one that names this instance's area.

    Left alone, a generated `ventas` cell would introduce itself as the finance
    assistant -- a wrong default in the one field a user actually reads.
    """
    marker = "  persona: >"
    start = template.find(marker)
    if start < 0:
        return template
    end = template.find("\n\n", start)
    if end < 0:
        return template
    persona = (
        marker
        + "\n"
        + f"    Asistente experto del area de {area.capitalize()}. Formal, preciso, cita\n"
        + "    siempre sus fuentes. Si no encuentra respaldo documental, lo dice en lugar\n"
        + "    de suponer."
    )
    return template[:start] + persona + template[end:]


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    name = args.name.strip().lower()
    tenant = args.tenant.strip().lower()

    for label, value in (("--name", name), ("--tenant", tenant)):
        if not NAME_PATTERN.match(value):
            print(
                f"{label} must be lowercase letters, digits and hyphens, 2-31 chars: got {value!r}",
                file=sys.stderr,
            )
            return 2

    slug = f"{tenant}-{name}"
    target = args.root / slug
    if target.exists() and not args.force:
        print(f"{target} already exists; pass --force to overwrite", file=sys.stderr)
        return 2
    if target.exists():
        shutil.rmtree(target)

    port = args.port or next_port(args.root)
    area = args.area or name
    target.mkdir(parents=True)

    fields = {
        "name": name,
        "tenant": tenant,
        "slug": slug,
        "api_port": port,
        "area": area,
        "shared_env": SHARED_ENV if args.shared else "",
        "mode_label": "compartido" if args.shared else "independiente",
        "mode_note": SHARED_NOTE if args.shared else STANDALONE_NOTE,
    }
    compose = SHARED_COMPOSE_TEMPLATE if args.shared else COMPOSE_TEMPLATE
    (target / ".env").write_text(ENV_TEMPLATE.format(**fields), encoding="utf-8")
    (target / "docker-compose.yml").write_text(compose.format(**fields), encoding="utf-8")
    (target / "README.md").write_text(README_TEMPLATE.format(**fields), encoding="utf-8")
    (target / "agent.profile.yaml").write_text(
        render_profile(
            TEMPLATE_PROFILE.read_text(encoding="utf-8"), name=name, tenant=tenant, area=area
        ),
        encoding="utf-8",
    )

    print(f"instance {slug} created at {target}")
    mode = "shared infrastructure" if args.shared else "standalone stack"
    print(f"  isolation : {mode}")
    print(f"  port      : 127.0.0.1:{port}")
    print(f"  profile   : {target / 'agent.profile.yaml'}")
    print("\nnext:")
    if args.shared:
        print("  make up PROFILE=core          # the base stack has to be up first")
    print(f"  cd instances/{slug}")
    print("  docker compose --env-file ../../.env --env-file .env --profile core up -d")
    print(f"  curl -s http://127.0.0.1:{port}/health/ready")
    print("\nno source file was modified.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
