"""Create a second cell that runs alongside the first. ``make new-instance``.

The point of the generator is what it does *not* do: it never touches code. A new area is
a new profile, a new ``.env`` and a Compose override with its own project name, ports and
volumes -- and that is the whole product claim. If adding an area required a code change,
this would be a framework, not a product.

The logical isolation is already there: every key in Redis, Postgres, Qdrant, Neo4j, NATS
and the ledger carries ``tenant_id`` and ``AGENT_FORGE_INSTANCE``. What the override adds
is host-level isolation -- two containers cannot both own port 8080 -- and that is a
deployment concern, not a correctness one.

    uv run python scripts/new_instance.py --name ventas --tenant acme-mx
    cd instances/acme-mx-ventas && docker compose up -d
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
INSTANCES = REPO_ROOT / "instances"
TEMPLATE_PROFILE = REPO_ROOT / "configs" / "agent.profile.example.yaml"

# Where the per-instance ports start. 8080 is the base cell, so the first generated
# instance takes 8180 and each one after it moves up by 100 -- enough room for the whole
# service block of an instance without overlapping the next.
PORT_BASE = 8080
PORT_STRIDE = 100
NAME_PATTERN = re.compile(r"^[a-z][a-z0-9-]{1,30}$")

ENV_TEMPLATE = """# Generated by `make new-instance NAME={name} TENANT={tenant}`.
#
# Only what differs from the base cell lives here. Everything else is inherited from the
# repository's `.env`, which is where shared infrastructure and secrets belong: two
# instances on one host share a Postgres, and duplicating its password into every
# instance directory is how one of the copies goes stale.

COMPOSE_PROJECT_NAME=agent-forge-{slug}

AGENT_FORGE_INSTANCE={name}
AGENT_FORGE_TENANT={tenant}
AGENT_FORGE_PROFILE=/app/configs/agent.profile.yaml

# Host ports. The container still listens on 8080; only the published side moves.
AGENT_API_PORT={api_port}
AGENT_PUBLIC_URL=http://127.0.0.1:{api_port}

# Evidence is per instance: one chain per tenant, and two instances writing the same
# chain would fork it, which fails verification in a way that looks like tampering.
LEDGER_PATH=/var/lib/agent-forge/ledger
"""

COMPOSE_TEMPLATE = """# Generated by `make new-instance NAME={name} TENANT={tenant}`.
#
# An override, not a copy. It includes the repository's compose file so a change there --
# a pinned image, a healthcheck, a resource limit -- reaches every instance. A generated
# full copy would drift from the original the first time anyone edited either.
#
#     cd instances/{slug}
#     docker compose --env-file ../../.env --env-file .env --profile core up -d
#
# Two env files, in that order: the repository's holds the shared infrastructure and its
# secrets, this one holds only what makes this instance different. Duplicating the
# secrets into every instance directory is how one of the copies goes stale.
#
# The published port comes from AGENT_API_PORT in this directory's `.env`; the base file
# already reads it, so there is nothing to override here.

include:
  - path: ../../deploy/compose/docker-compose.yml

services:
  agent-api:
    environment:
      AGENT_FORGE_INSTANCE: {name}
      AGENT_FORGE_PROFILE: /app/configs/agent.profile.yaml
    volumes:
      # This instance's profile shadows the image's default.
      - ./agent.profile.yaml:/app/configs/agent.profile.yaml:ro
      - {slug}-ledger:/var/lib/agent-forge/ledger

  ingestion-worker:
    environment:
      AGENT_FORGE_INSTANCE: {name}
      AGENT_FORGE_PROFILE: /app/configs/agent.profile.yaml
    volumes:
      - ./agent.profile.yaml:/app/configs/agent.profile.yaml:ro
      - {slug}-ledger:/var/lib/agent-forge/ledger

volumes:
  {slug}-ledger:
"""

README_TEMPLATE = """# Instancia `{name}` · tenant `{tenant}`

Generada por `make new-instance NAME={name} TENANT={tenant}`. **No se edito codigo.**

```bash
cd instances/{slug}
docker compose --env-file ../../.env --env-file .env --profile core up -d
curl -s http://127.0.0.1:{api_port}/health/ready | jq
```

Los dos `--env-file` y en ese orden: el del repositorio trae la infraestructura
compartida y sus secretos, el de aqui solo lo que hace distinta a esta instancia.

## Que la separa de la celula base

| Dimension | Como se separa |
|---|---|
| Datos | Cada clave en Redis, Postgres, Qdrant, Neo4j y NATS lleva `tenant_id` + instancia |
| Evidencia | Cadena hash propia, en su volumen |
| Puerto | `{api_port}` en el host; dentro del contenedor sigue siendo 8080 |
| Proyecto Compose | `agent-forge-{slug}`, asi que sus contenedores, redes y volumenes son suyos |
| Perfil | `agent.profile.yaml` en este directorio, montado sobre el de la imagen |

## Que comparte

La infraestructura: Postgres, Redis, Qdrant, NATS, LiteLLM y el stack de observabilidad
del `docker-compose.yml` del repositorio. Es lo que hace barata la segunda instancia. Si
un tenant necesita aislamiento fisico, eso es otro despliegue, no otra instancia.

## Personalizar

Edita `agent.profile.yaml`: area, persona, subgrafo, fuentes de conocimiento, mapa de
autonomia, allowlist de tools. Reinicia con `docker compose restart agent-api`. Sigue sin
tocarse codigo.
"""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--name", required=True, help="instance name, e.g. ventas")
    parser.add_argument("--tenant", required=True, help="tenant id, e.g. acme-mx")
    parser.add_argument("--area", default="", help="business area (defaults to --name)")
    parser.add_argument("--port", type=int, default=0, help="host port (default: next free)")
    parser.add_argument(
        "--force", action="store_true", help="overwrite an existing instance directory"
    )
    parser.add_argument("--root", type=Path, default=INSTANCES)
    return parser.parse_args(argv)


def next_port(root: Path) -> int:
    """The next port in the stride that no existing instance has taken."""
    used = set()
    for env in sorted(root.glob("*/.env")):
        for line in env.read_text(encoding="utf-8").splitlines():
            if line.startswith("AGENT_API_PORT="):
                with_value = line.split("=", 1)[1].strip()
                if with_value.isdigit():
                    used.add(int(with_value))
    port = PORT_BASE + PORT_STRIDE
    while port in used:
        port += PORT_STRIDE
    return port


def render_profile(template: str, *, name: str, tenant: str, area: str) -> str:
    """Point the example profile at this instance.

    A targeted rewrite of the identity block rather than a generated file: the example
    profile is the documented reference, comments included, and a generator that produced
    its own minimal version would quietly drop everything the reference explains.
    """
    template = _replace_persona(template, area)
    lines = template.splitlines()
    out: list[str] = []
    in_identity = False
    for line in lines:
        if line.startswith("identity:"):
            in_identity = True
            out.append(line)
            continue
        if in_identity and line and not line.startswith((" ", "#")):
            in_identity = False
        if in_identity:
            for key, value in (
                ("agent_name:", f'"asistente-{name}"'),
                ("area:", f'"{area}"'),
                ("tenant_id:", f'"{tenant}"'),
            ):
                stripped = line.strip()
                if stripped.startswith(key):
                    indent = line[: len(line) - len(line.lstrip())]
                    comment = line.split("#", 1)
                    trailing = f"  #{comment[1]}" if len(comment) > 1 else ""
                    line = f"{indent}{key} {value}{trailing}"
                    break
        out.append(line)
    header = (
        f"# Perfil de la instancia `{name}` (tenant `{tenant}`).\n"
        f"# Generado por `make new-instance`. Editable: es configuracion, no codigo.\n"
    )
    return header + "\n".join(out) + "\n"


def _replace_persona(template: str, area: str) -> str:
    """Swap the example persona for one that names this instance's area.

    Left alone, a generated `ventas` cell would introduce itself as the finance
    assistant -- a wrong default in the one field a user actually reads.
    """
    marker = "  persona: >"
    start = template.find(marker)
    if start < 0:
        return template
    end = template.find("\n\n", start)
    if end < 0:
        return template
    persona = (
        marker
        + "\n"
        + f"    Asistente experto del area de {area.capitalize()}. Formal, preciso, cita\n"
        + "    siempre sus fuentes. Si no encuentra respaldo documental, lo dice en lugar\n"
        + "    de suponer."
    )
    return template[:start] + persona + template[end:]


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    name = args.name.strip().lower()
    tenant = args.tenant.strip().lower()

    for label, value in (("--name", name), ("--tenant", tenant)):
        if not NAME_PATTERN.match(value):
            print(
                f"{label} must be lowercase letters, digits and hyphens, 2-31 chars: got {value!r}",
                file=sys.stderr,
            )
            return 2

    slug = f"{tenant}-{name}"
    target = args.root / slug
    if target.exists() and not args.force:
        print(f"{target} already exists; pass --force to overwrite", file=sys.stderr)
        return 2
    if target.exists():
        shutil.rmtree(target)

    port = args.port or next_port(args.root)
    area = args.area or name
    target.mkdir(parents=True)

    fields = {
        "name": name,
        "tenant": tenant,
        "slug": slug,
        "api_port": port,
        "area": area,
    }
    (target / ".env").write_text(ENV_TEMPLATE.format(**fields), encoding="utf-8")
    (target / "docker-compose.yml").write_text(COMPOSE_TEMPLATE.format(**fields), encoding="utf-8")
    (target / "README.md").write_text(README_TEMPLATE.format(**fields), encoding="utf-8")
    (target / "agent.profile.yaml").write_text(
        render_profile(
            TEMPLATE_PROFILE.read_text(encoding="utf-8"), name=name, tenant=tenant, area=area
        ),
        encoding="utf-8",
    )

    print(f"instance {slug} created at {target}")
    print(f"  port      : 127.0.0.1:{port}")
    print(f"  profile   : {target / 'agent.profile.yaml'}")
    print("\nnext:")
    print(f"  cd instances/{slug}")
    print("  docker compose --env-file ../../.env --env-file .env --profile core up -d")
    print(f"  curl -s http://127.0.0.1:{port}/health/ready")
    print("\nno source file was modified.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
